### ISSUE TITLE
Nasty compiler bug

### ISSUE THREAD

**Issue by dominicwilliams** [chriseth/browser-solidity#103]
This cost me some hours, lol

```
if (pile.size > 0) {
  // search...
  uint64 prev = NIL;
  uint64 curr = pile.top;
  while (true) {
    Order co = pile.orders[curr];
    bool insert = false;
    // bid?
    if (pile.orderType == BID) {
      if (o.price > co.price)
        insert = true;
    }
    // ask
    else { // if (pile.type == ASK) {
      if (o.price < co.price)
        insert = true;
    }
    // insert here?
    if (insert) {
      o.above = prev;
      o.below = curr;
      break;
    }
    // COMPILER BUG
    // The magic line following this comment is necessary for correct behavior.
    // Without the following line, the compiler treats prev = curr as a reference assignment (I
    // am new to Solidity, but this is surely a value assignment?).
    // Thus "o.above = prev;" becomes "o.above = co.below";
    uint64 abracadabra = curr;
    // move down
    prev = curr;
    curr = co.below;
    // bottom?
    if (curr == NIL) {
      o.above = prev;
      o.below = NIL;
      break;
    }
  }
}
```

**Comment by chriseth** [comment]
Thanks for the bug report! Could you please post the full source, potentially maximally stripped down plus the expected and observed behaviour, compiler version and options (optimizer used / not used)?

**Comment by dominicwilliams** [comment]
Hi it's solc 0.2.1-1, which is a dependency of the latest truffle.

I can't post the full project source yet unfortunately (company plans to release a complete working system later) but will try later today to reproduce the bug using standalone example code.

Nb1. looks like solc is treating uint64=uint64 as a reference assignment. Might be easy to see in original C++ source. Alternatively, wondering if Javascript version being fooled by uint64 prev = NIL statement. In my code NIL is a constant 0xffffffffffffffff but perhaps name mangling went wrong (and seeing a nil value being assigned, makes it a reference). 

Nb2. Unit tests were passing previously but not sure if prob caused by upgrading solc or gentle refactoring.

**Comment by chriseth** [comment]
Sorry, my previous comment was probably phrased unclearly. Please provide a complete source (i.e. full contract) that compiles and shows the error, potentially as short as possible.

**Comment by axic** [comment]
@dominicwilliams if the problem still persists, can you please report it to https://github.com/ethereum/solidity?
