### ISSUE TITLE
Error: Intrinsic gas too low

### ISSUE THREAD

**Issue by kartojal** [chriseth/browser-solidity#104]
im trying to "suicide(owner)" via this function

```
[...]
modifier onlyowner { 
        if (msg.sender != owner) throw;
        _
    }
[...]
function killContract() onlyowner{
        suicide(owner);
    }
[...]
```

but in browser-solidity when i "press" and call killContract() function , this happens: 
Error: Intrinsic gas too low

i'm connected to my own geth node with testnet Morden, fully synced. All other functions of the contract works like a charm.

How can i get rid of that error? can be a bug?

**Comment by msfeldstein** [comment]
Did you ever figure this out?  I'm seeing something similar and my guess is that it's working correctly, if it throw's it should fail right?  I think it might just be that it's treating throw like a VERY expensive operation, and failing that way.

**Comment by axic** [comment]
This should be fixed since `eth_estimateGas` is called before execution and also there is an option in the UI to set a gas limit.

**Comment by chriseth** [comment]
Please reopen if the issue persists.

**Comment by brendan87** [comment]
I'm seeing the intrinsic gas too low for the following simple contract. I can add new members to the array but when I try to run "removeHolder" it appears.

```
contract testA {
    address[] public holders;
    function addHolder(address newHolder) {
        holders.push(newHolder);
    }
    function removeHolder() {
        delete holders[holders.length-1];
    }
}
```

Note that this is when connected to a local geth node (1.5.0-unstable), and does not occur when running on the browser javascript vm.
