### ISSUE TITLE
Editor: Make line length rule configurable

### ISSUE THREAD

**Issue by zach-is-my-name** [chriseth/browser-solidity#109]
The vertical line bisecting the work space is distracting in my case.  Is there a way of implementing a toggle switch for it?

Please see my Stack Exchange [question](http://ethereum.stackexchange.com/questions/1560/whats-the-purpose-of-the-vertical-rule-dividing-the-work-space-in-browser-solid/1566#1566) for screenshot and further description.

**Comment by axic** [comment]
This is tracked now in https://github.com/ethereum/browser-solidity/issues/150.
