### ISSUE TITLE
Use NO_DYNAMIC_EXECUTION in compilation (removes "eval" which is considered evil)

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#110]
Looks like there's at least one eval in the browser solidity code. It makes me nervous having evals anywhere. Is it possible to use a different technique?

Ps, not sure if this is an upstream issue. I can move there if it is.

https://raw.githubusercontent.com/chriseth/browser-solidity/gh-pages/bin/soljson-latest.js

**Comment by chriseth** [comment]
There seems to be a compiler flag to fix this.

**Comment by chriseth** [comment]
Added the compiler flag, the next binary should be available soon (I think it needs an actual change in the source). Please check in some days.

**Comment by aakilfernandes** [comment]
:+1:

**Comment by chriseth** [comment]
Seems to be fixed, at least I cannot find `eval` in the js file.
