### ISSUE TITLE
string4/string32 undeclared identifier

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#111]
I'm trying out the generic call method example, which does not compile

https://github.com/ethereum/wiki/wiki/Solidity-Features#generic-call-method

```
contract test {
  function f(address addr, uint a) {
    addr.call(string4(string32(sha3("fun(uint256)"))), a);
  }
}
```

**Comment by chriseth** [comment]
The "features" page is not meant as an up to date list of features but rather for historical reference. Please use `bytes4` or `bytes32` instead of `string4` and `string32`.

**Comment by aakilfernandes** [comment]
Will do. Thanks.
