### ISSUE TITLE
Pressing Crtl+T in Firefox re-arranges characters in the editor instead of opening a new tab

### ISSUE THREAD

**Issue by ethernomad** [chriseth/browser-solidity#112]
This behaviour is sort of weird. On Chromium it is fine. Crtl+T opens a new tab.

But on Firefox if I click in the text editor area. Ctrl+T re-arranges the characters around the cursor.

**Comment by chriseth** [comment]
The shortcut is captured by the editor we use, I'll see what I can do.

**Comment by axic** [comment]
The solution to remove is explained here: https://github.com/ajaxorg/ace/issues/36#issuecomment-6941120
