### ISSUE TITLE
Uncaught TypeError: soljson.cwrap is not a function

### ISSUE THREAD

**Issue by ethereumdegen** [chriseth/browser-solidity#113]
I get error 'Uncaught TypeError: soljson.cwrap is not a function' and it points to the following line:
`var compileJSON = soljson.cwrap("compileJSON", "string", ["string", "number"]);`

I am running this in rails using browserify-rails and am using node 4.3.1

**Comment by chriseth** [comment]
Could you check what `soljson` is? It seems that the main module is not loaded correctly.

**Comment by croqaz** [comment]
Same issue here, when importing solc from Electron;

console.log(soljson); // Object {}

**Comment by chriseth** [comment]
@croqaz @admazzola please give a bit more info about your environment. It seems that the `require` call fails.

**Comment by croqaz** [comment]
```
node -v // v4.3.1
npm -v // 3.7.5
electron -v // v0.36.9
npm install solc
└── solc@0.2.2-2 
```

Install electron-prebuilt; Use this HTML in main BrowserWindow;

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Hello!</title>
</head>
<body>
  <h3>Hi</h3>
  <script> console.log( require('solc') ); </script>
</body>
</html>
```

Hack node_modules/solc/index.js to add `console.log( soljson )`;

![solc2](https://cloud.githubusercontent.com/assets/1748317/13498853/4f515d48-e164-11e5-9da9-1a6969b37dec.png)

In command line, electron writes this:
electron .
[Emscripten Module object]
[Function: cwrap]

So apparently, this works on the server side, but not on the client side;

**Comment by frozeman** [comment]
Note that electron when you have `node-integration` turned on in the browser window (default on) then electron provides a require, which has nothing to do with the require you may want.

turn node integration of using:

``` js

new BrowserWindow({
   webPreferences: {
       nodeIntegration: false
   }
})
```

**Comment by AustP** [comment]
I'm having this same issue. I am trying to include solc inside of an Atom package. (Atom runs on electron but I have no control over `node-integration`.) The require call to `soljson.js` always returns an empty object.

**Comment by axic** [comment]
@Denton-L perhaps it makes sense documenting @frozeman's tip in https://github.com/ethereum/solc-js?

**Comment by Denton-L** [comment]
Alright, will do so.
