### ISSUE TITLE
Non-numeric byte strings cause a crash

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#114]
Compiles:

```
contract C1 {
    function f1() constant returns(bytes) {
        bytes memory bb = "\x00\x01\x04"; 
        return(bb);
    }
}
```

Crashes:

```
contract C1 {
    function f1() constant returns(bytes) {
        bytes memory bb = "\x00\x01\xa4"; 
        return(bb);
    }
}
```

**Comment by axic** [comment]
Can you please elaborate what crashing means? Are you seeing the same problem as in #132?

@aakilfernandes tried with 0.3.2 of solc (not solc-js or browser-soldity) and it works. Is it still crashing for you?

**Comment by aakilfernandes** [comment]
@axic I'm referring to browser solidity https://chriseth.github.io/browser-solidity/#version=soljson-v0.3.2-2016-05-17-0a37072.js&optimize=true

**Comment by aakilfernandes** [comment]
No error is given and I can see erros in the js console

**Comment by axic** [comment]
Can you copy paste those errors please?

**Comment by aakilfernandes** [comment]
```
Uncaught SyntaxError: Unexpected token :
```

![screen shot 2016-05-21 at 12 15 15 pm](https://cloud.githubusercontent.com/assets/1577353/15449505/bfcc8f76-1f4d-11e6-95b3-062b50aa632f.png)

**Comment by axic** [comment]
@aakilfernandes I see.

It is two problems:
- Catch exceptions in JSON parsing of the solc response (I thought I've had a PR for this - will do it later)
- And the same problem as described in #132. (Even though it was reported later, that thread has more details available.)

**Comment by aakilfernandes** [comment]
Got it, will follow #132
