### ISSUE TITLE
browser documentation

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#115]
Hi, how do I actually use this in a browser? I don't see a dist folder. Does it need to be browserified? Additional documentation would be helpful.

**Comment by chriseth** [comment]
Documentation is here: https://github.com/chriseth/browser-solidity#browser-solidity
This is both a html user interface and a compiler-only npm package.

**Comment by aakilfernandes** [comment]
Id like to use the compiler client side (similar to how you do it). That documentation only works in node environments.

**Comment by aakilfernandes** [comment]
Hi, any thoughts on this?

**Comment by d11e9** [comment]
@aakilfernandes you can use browserify to use the npm package clientside.

OR have a look at the code, and see how its used in the browser main file `aap.js` https://github.com/piratechest/piratechest-raid.git
https://github.com/chriseth/browser-solidity/blob/gh-pages/assets/js/app.js#L453

which is pretty much the same way its used in the small npm `index.js https://github.com/piratechest/piratechest-raid.git
https://github.com/chriseth/browser-solidity/blob/gh-pages/assets/js/app.js#L453
https://github.com/chriseth/browser-solidity/blob/gh-pages/index.js#L3-L7`

```
// Assuming soljson-latest.js in already loaded in page (exposing the `Module` below
var compileJSON = Module.cwrap("compileJSON", "string", ["string", "number"]);
var compiled = compileJSON("contract S {}", shouldOptimize);
```

**Comment by aakilfernandes** [comment]
Trying out browserify, but struggling with it. Looks like something is funky where `require('./bin/soljson-latest.js')` returns undefined

I took a look at the code in the example. I'm hesitant to follow that route since it seems to add a bunch of globals without any documentation.

**Comment by axic** [comment]
@aakilfernandes perhaps you are running into the same issue as here: https://github.com/chriseth/browser-solidity/issues/113 ?

**Comment by axic** [comment]
@aakilfernandes also solc-js has been moved to its own repo: https://github.com/ethereum/solc-js. It has a more comprehensive README too.

**Comment by axic** [comment]
@aakilfernandes It needs to be browserified. Instructions are here: https://github.com/ethereum/browser-solidity#building

The latest version also creates a ZIP file with every commit, available here: https://github.com/ethereum/browser-solidity/tree/gh-pages
