### ISSUE TITLE
Serve binaries from different repository

### ISSUE THREAD

**Issue by holgerd77** [chriseth/browser-solidity#116]
Hi, I thought I could maybe contribute a bit to the UI of `browser-solidity` and wanted to clone the repo but actually gave up due to downloading times and volume (working on mobile conn right now).

Would it be possible to extract the `bin` folder and serve soljson files from Amazon S3? I think that would generally ease contribution workflow and make things fluffier.
- [x] copy binaries to https://github.com/ethereum/solc-bin
- [x] create special index of "release" binaries (first binary with new version number)
- [x] update jenkins job to push new binaries there
- [x] update browser-solidity and npm packages to use binaries from there

**Comment by chriseth** [comment]
I'm pretty sure github already uses S3, but we could profit from separating code and binaries, yes.

**Comment by chriseth** [comment]
Use this repository: https://github.com/ethereum/solc-bin

**Comment by winsvega** [comment]
https://github.com/ethereum/solc-bin/pull/1

**Comment by chriseth** [comment]
Updating the npm will be done in a separate task, the one that splits off the npm package itself.
