### ISSUE TITLE
Update ethereum-js

### ISSUE THREAD

**Issue by chriseth** [chriseth/browser-solidity#117]
It seems that the version of ethereum-js we are using does not support DELEGATECALL.

**Comment by axic** [comment]
I have actually looked at making `universal-dapp` compatible with the current `ethereumjs-vm` and there were couple of changes required. You should definitely use the latest though as there were countless bug fixes. I think you're still using a version back from October?

**Comment by axic** [comment]
Well, I guess it was time dusting down my patch: https://github.com/d11e9/universal-dapp/pull/9

**Comment by axic** [comment]
Seems like maintenance of universal-dapp moved into here, so made a PR against this repo: https://github.com/chriseth/browser-solidity/pull/119

**Comment by chriseth** [comment]
Fixed in https://github.com/chriseth/browser-solidity/pull/119 - thanks a lot, @axic !
