### ISSUE TITLE
Question. How to catch exceptions in solc nodejs

### ISSUE THREAD

**Issue by mtbitcoin** [chriseth/browser-solidity#120]
Is it possible to catch exceptions when running the solc nodejs?

var solc = require('solc');
var input = "contract xExceptionFunction { functionXXError g() {} }";
var output = solc.compile(input, 1); // 1 activates the optimiser
for (var contractName in output.contracts) {
    // code and ABI that are needed by web3
    console.log(contractName + ': ' + output.contracts[contractName].bytecode);
    console.log(contractName + '; ' + JSON.parse( output.contracts[contractName].interface));
}

**Comment by chriseth** [comment]
Could you please be a bit more specific? It is a known problem that emscripten kind of messes with the exception handler of nodejs. Is that what you are talking about?

**Comment by mtbitcoin** [comment]
I trying to see if I can catch an exception by doing something like this, but the exception never gets called in nodejs. 

var solc = require('solc');
var input = "contract someBadFunctionHere { functionXXError g() {} }";
try { 
    var output = solc.compile(input, 1); // 1 activates the optimiser
    for (var contractName in output.contracts) {
    // code and ABI that are needed by web3
    console.log(contractName + ': ' + output.contracts[contractName].bytecode);
    console.log(contractName + '; ' + JSON.parse( output.contracts[contractName].interface));
} catch (exception) { 
   // This exception never gets called
    Console.log('Uncaught JavaScript exception:\n' + exception); 
}

**Comment by chriseth** [comment]
Where does the excption come from? I don't see a `throw` in your code. Can you provide a stack trace / error log?
