### ISSUE TITLE
FeatureRequest: Additional gist integration parameters

### ISSUE THREAD

**Issue by mtbitcoin** [chriseth/browser-solidity#121]
At the moment its possible to do something like https://chriseth.github.io/browser-solidity/?gist=f9aa1278818ef2f022fd , which is extremely helpful. But what would even be better is the ability to also set the "optimizer" and "compiler versions" via querystring. So it should end up something like were we can past both the compiler version and optimization settings

https://chriseth.github.io/browser-solidity/?gist=f9aa1278818ef2f022fd&compiler=v.x.x.x.x&optimizer=1

**Comment by d11e9** [comment]
:+1:

**Comment by chriseth** [comment]
@d11e9 would you like to implement that? :-)

**Comment by d11e9** [comment]
@chriseth sure.

**Comment by d11e9** [comment]
Addressed in above PR. #133

**Comment by d11e9** [comment]
Example gist output with url: https://gist.github.com/anonymous/2b89b986cc178b0b548d94cbe7dfe692
