### ISSUE TITLE
Line breaks changes bytecodes?

### ISSUE THREAD

**Issue by mtbitcoin** [chriseth/browser-solidity#123]
I am not sure if this is a feature or an issue. But I noticed that on certain contracts the line breaks changes the contract bytecode. Is this a feature or an issue. The following settings and contract was used :
- latest compiler (2016-03-18), optimize enabled
- https://chriseth.github.io/browser-solidity/?gist=3ce55235bc7def2b9edda3c76b6a8b7d

If you modify the contract above by adding additional line breaks (enter key in windows Chrome) at the top , it produces a slightly different byte code. Shouldn't the online compiler normalize the contract code by disregarding line breaks before producing the bytecode ??

**Comment by androlo** [comment]
On a related note, it also messes up the assembly output (at least for me in chrome, with my resolution etc.). 

```
contract C {
    function f(){}
}
```

Type that in, then look at assembly. Now add an empty line between contract definition and function, and it gets much harder to read.

**Comment by androlo** [comment]
It's as if annotations are being put on a separate, new line, rather then to the right of the instruction.

**Comment by androlo** [comment]
Oh. Some escaped newline characters in there as well. I don't see those in the console.

**Comment by mtbitcoin** [comment]
looking back this issue could be related to the ... "AST nodes are identified by their raw pointers, if we iterate over data structures, different raw pointers might result in different iteration order"

One possible explanation is when the line breaks are introduced, it forces a recompile which produces slightly different byte code not because of the line break itself but the AST issue above.

**Comment by axic** [comment]
I think this probably was resolved by https://github.com/ethereum/solidity/pull/536.
