### ISSUE TITLE
Use proper npm dependency / build process

### ISSUE THREAD

**Issue by chriseth** [chriseth/browser-solidity#125]
- [x] use proper npm build process to fetch dependencies and build website (gh-pages)
- [x] create travis (or jenkins) job to auto-build the website
- [x] remove binaries and move website to ethereum/browser-solidity (the idea is to keep the git small)
- [x] make npm package private (not much sense in publishing, we mostly use the build system)
- [x] change readme and add link to gh-pages
- [x] add warning that site has moved (and explain how to move data in local storage)

**Comment by axic** [comment]
Especially these parts would be nice to have independently browserified:
- ace.js
- the minified base64 code in front of app.js
- ethereumjs(-vm)
- web3

**Comment by chriseth** [comment]
Preliminary work here: https://github.com/ethereum/browser-solidity/tree/npmify
