### ISSUE TITLE
Function parameter parsing for Arrays/Mappings bug when connected to Web3Provider endpoint

### ISSUE THREAD

**Issue by ealkalai** [chriseth/browser-solidity#134]
I have an array (any kind) and I want to access its values. When I do this through the virtual machine, everything seems to work fine.
However, when I am connected to an ethereum web3 provider endpoint I only receive the first element. After some digging around, I noticed that the json request that is sent is wrong no matter what is the index I place in the text box. It's always zero (0).

**Comment by axic** [comment]
@ealkalai can you elaborate please with examples? Is it still reproducible?
