### ISSUE TITLE
Incorrect gas costs for some functions

### ISSUE THREAD

**Issue by Arachnid** [chriseth/browser-solidity#137]
For the following contract:

```
contract StringUtils {
    function strstr(string haystack, string needle, uint idx) returns (int) {
        uint needleSize = bytes(needle).length;
        bytes32 hash = sha3(needle);
        for(; idx < bytes(haystack).length - needleSize; idx++) {
            bytes32 testHash;
            assembly {
                testHash := sha3(add(add(haystack, idx), 32), needleSize)
            }
            if (hash == testHash)
                return int(idx);
        }
        return -1;
    }
}
```

Creating the contract, then executing the included function with sample arguments (say, "fooooo", "oo", 0) shows very high gas cost on the order of 25k. Running the function a second time returns a much lower figure, on the order of 1000 gas. Neither figure matches up with the result from the morden testnet, which reports a figure on the order of 2500 gas.

In Firefox, the same high gas cost is returned each time.

**Comment by Arachnid** [comment]
Simple functions returning string also cause this:

```
contract Test {
    function foo() returns (string) {
        return "foobar";
    }
}
```

A simple function returning uint doesn't.

**Comment by axic** [comment]
Fixed in https://github.com/ethereum/browser-solidity/pull/19.

The reason there is a difference between `uint` and `string` is the in the latter case Solidity still uses the identity contract and that triggers the extra fee on first call as explained in the fix.
