### ISSUE TITLE
How to pass constructor arguements during contract compilation in nodejs ?

### ISSUE THREAD

**Issue by mtbitcoin** [chriseth/browser-solidity#138]
For certain contracts like this one https://chriseth.github.io/browser-solidity/?gist=711084cfc030da907a9a8a249228a871 , it accepts the following arguements :

-- under the 'order' contract --
var _token = /\* var of type address here _/ ;
var _weiPerToken = /_ var of type uint256 here _/ ;
var _decimalPlaces = /_ var of type uint256 here */ 

In nodejs, is there way to programatically pass in these custom arguements?

**Comment by chriseth** [comment]
You have to use web3.js for that and you do not do it during compilation. You pass constructor arguments by appending the ABI-encoded values to the bytecode.

**Comment by mtbitcoin** [comment]
thanks
