### ISSUE TITLE
Other Legacy Versions?

### ISSUE THREAD

**Issue by ricmoo** [chriseth/browser-solidity#146]
Heya!

I was wondering if there are other released versions of solidity that don't have a corresponding `soljson`?

I'm trying to verify the etherID.org contract and have been having some issues. I've got a script that compiles it against all version, and it comes _close_, very, ridiculously close, and I was wondering if maybe it makes sense to you.

Basically after compiling, I run this function against the two files (the compiled and the one the blockchain):

``` javascript
// Find the positions that two buffers differ
function diff(a, b) {
    for (var i = 0; i < a.length; i++) {
        if (a[i] !== b[i]) { console.log(i, a[i], b[i]); }
    }
}
```

to which I get the following results:

```
164 182 173
315 173 182
468 0 1
477 1 0
```

So, the bytes at index 164 and 315 are swapped and bytes 468 and 477 have been swapped.

Any ideas? Is there perhaps other legacy versions we should build and include?

**Comment by ricmoo** [comment]
I've expanded the EVM code, if this helps. Perhaps the ordering of output functions was changed?

[compiled.txt](https://github.com/chriseth/browser-solidity/files/225391/compiled.txt)
[expected.txt](https://github.com/chriseth/browser-solidity/files/225392/expected.txt)

Here is the diff:

```
/Users/ricmoo/Development/ethers> diff target.evm compiled.evm | more
74,76c74,76
< PUSH2 0x01ad
< JUMP 0x01ad
< JUMPDEST 0x01ad
---
> PUSH2 0x01b6
> JUMP 0x01b6
> JUMPDEST 0x01b6
163,165c163,165
< PUSH2 0x01b6
< JUMP 0x01b6
< JUMPDEST 0x01b6
---
> PUSH2 0x01ad
> JUMP 0x01ad
> JUMPDEST 0x01ad
283c283
< PUSH1 0x01
---
> PUSH1 0x00
290c290
< PUSH1 0x00
---
> PUSH1 0x01
```

**Comment by chriseth** [comment]
Your evm assembly representation is a bit strange, but it seems that the code is actually different. In one version, some value is loaded from storage position 0, in the other, it is loaded from position 1.

**Comment by axic** [comment]
@chriseth could that be caused by the problem https://github.com/ethereum/solidity/pull/536 fixes? Or perhaps they have swapped two method arguments?

@ricmoo if that is the case you have to run the same version of the compiler you have identified several times and see if it comes up with the same code.

**Comment by axic** [comment]
@ricmoo is this still an issue? Did you find a solution? Perhaps you could reopen this bug in ethereum/solidity with keeping a link to here. Otherwise please close.

Make sure to you have tested this:

> @ricmoo if that is the case you have to run the same version of the compiler you have identified several times and see if it comes up with the same code.
