### ISSUE TITLE
The VM reports this contract runs out of gas to deploy

### ISSUE THREAD

**Issue by StevenBerryman** [chriseth/browser-solidity#147]
I have attached a copy of a contract which the VM reports runs out of gas when deployed. I upped the gas in the javascript app.js with no luck. The problems seems to be in the concatenation of the bytecodes with the contract creation string. It could be because the bytecode string is too long to be concatenated in this way. I think the reason it reports out of gas is that part of the string never makes it into the code variable.

[weatherOracle.txt](https://github.com/chriseth/browser-solidity/files/225964/weatherOracle.txt)

**Comment by chriseth** [comment]
The source you linked contains several copy-past errors, but after resolving them, I can deploy the contract with a bit more than 1 million gas. Does the creation run out of gas or some of the functions?

**Comment by StevenBerryman** [comment]
Sorry about the copy and paste errors. It's bit strange as I can take the string from the browser and paste it into my geth session and all works fine so it must be something to do with streaming it over the RPC connection. Do you know if there is anyway I can see what was run in my geth session from the RPC connection? Nothing gets written to the history so I'm not actually sure what it run and as I say copying the string from the browser and pasting it into geth works. Smaller contracts work fine its just this larger contract. Also I'm running on my own dev chain but don't think this should make a difference.

I'm running on Ubuntu and tested it using both firefox and Crome without any success. Thanks

**Comment by chriseth** [comment]
You can try actually connecting browser-solidity with geth (or open browser-solidity inside mist) and create contracts and execute functions using the buttons inside browser-solidity.

**Comment by ed-ilyin** [comment]
I have similar problem when trying to deploy contract thru Web3 Provider geth, deployment runs out of 1000000 of gas when more then 2000000 is needed:
http://ethereum.github.io/browser-solidity/#version=soljson-latest.js&optimize=true&gist=54a6df466349f65940f39d55aa5ee7f2
To reproduce deploy through Web3 Provider OylooBet contract with following parameters:
"Who will be the next president of USA?","DT=Donald Trump,HC=Hillary Clinton",1,15,1467288000,4

**Comment by axic** [comment]
@edvail this was solved by https://github.com/ethereum/browser-solidity/pull/125

I think it is safe to close this issue
