### ISSUE TITLE
Warning about unbounded gas usage

### ISSUE THREAD

**Issue by chriseth** [chriseth/browser-solidity#152]
Browser-solidity should show a warning in the source if a function has unbounded gas requirements (this already caused some problems several times). For the fallback functions, this warning should already be triggered if the gas requirement goes beyond the stipend.

One problem we might have here is that gas required by sub-calls is not taken into account by the estimator.

**Comment by axic** [comment]
Isn't this an issue for the solidity repo instead?

**Comment by chriseth** [comment]
Might be, but this is a feature for browser-solidity.

**Comment by axic** [comment]
@chriseth so basically you're looking for a more user-friendly presentation of the gas estimator output?

**Comment by chriseth** [comment]
Yes, but this should also be a special warning as part of the static analysis tab.

**Comment by chriseth** [comment]
Moved: https://github.com/ethereum/browser-solidity/issues/162
