### ISSUE TITLE
Wrong output for simple static array return

### ISSUE THREAD

**Issue by czepluch** [chriseth/browser-solidity#156]
If this code is run in browser-solidity with for example 1 and 2 as arguments, a wrong output is shown.

```
contract Test {
    function add(uint i, uint j) returns (uint[2] a) {
        a[0] = i;
        a[1] = j;
    }
}
```

output `1. uint256[2] a: 1, 0`, but it should be `1. uint256[2] a: 1, 2`
The raw output has the correct output though.

**Comment by axic** [comment]
Thanks @czepluch, this seems actually to be a bug in ethereumjs-abi. See https://github.com/ethereumjs/ethereumjs-abi/issues/13
