### ISSUE TITLE
Where does soljson.js come from?

### ISSUE THREAD

**Issue by redsquirrel** [chriseth/browser-solidity#157]
From what I understand, `soljson.js` is generated from C/C++ code. Is that right?

I've tried (in vain) to find how `soljson.js` is generated, or where it's generated from. Can anyone point me in the right direction?

Hopefully the answer isn't super-obvious! 😊

**Comment by chriseth** [comment]
Basically this script is used to compile it: https://github.com/ethereum/webthree-helpers/blob/develop/scripts/build_emscripten.sh

**Comment by redsquirrel** [comment]
Thanks @chriseth!

**Comment by axic** [comment]
A cross-reference for those trying to find it: #82
