### ISSUE TITLE
Display address transactions are being sent from

### ISSUE THREAD

**Issue by ethernomad** [chriseth/browser-solidity#19]
Sometimes I want to know what address transactions are being sent from in the javascript runtime environment. It's easy to add it temporarily to my contract, but if it could just be displayed automatically on the page it would be great!

**Comment by d11e9** [comment]
It is top right `tx.origin` is it not?

**Comment by ethernomad** [comment]
Ah - I didn't see that before. Is it new?

**Comment by d11e9** [comment]
yup :)

**Comment by ethernomad** [comment]
Cool!
