### ISSUE TITLE
Display errors correctly for imported sources

### ISSUE THREAD

**Issue by chriseth** [chriseth/browser-solidity#24]
browser-solidity currently imports other files manually and does not use the features provided by the copmiler (due to a missing interface). The result is that errors are not displayed at the right locations.
Change `jsonCompiler` to provide the right interface, so that it does import resolution and reports file names together with line numbers on errors.
Change browser-solidity so that it is able to parse these file names.

**Comment by d11e9** [comment]
:+1:

**Comment by VoR0220** [comment]
:+1:
