### ISSUE TITLE
Optimize

### ISSUE THREAD

**Issue by farming-potatoes** [chriseth/browser-solidity#3]
Hello. Wasn't sure where to post this. Is there anywhere that explains how your optimize function works? I would love to use it for my website to have it optimize a users code. Is there a way I can extract this function? Thanks

**Comment by chriseth** [comment]
I am not sure if we are talking about the same thing here.
The "optimize" checkbox activates the ethereum virtual machine bytecode optimizer inside the solidity compiler. If you want to use that, simply pass `true` as the second argument to the compile function. If you want to know how it works internally, [here](https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#internals-the-optimizer) are some high-level explanations.
