### ISSUE TITLE
`constant` functions update contract state

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#4]
Real time compiler is too forgiving. The `addBuyer` function shouldn't update the contract since it has the `constant` modifier, but the realtime compiler indicates that it does.

Run Lotto.addBuyer(10,10) then Lotto.getBuyerAddrs(). Works in the realtiem compiler but not locally. Not exactly sure where to submit this issue. Sorry if this is the wrong place.

```
contract Lotto {
    uint blocksPerRound=6800;

    struct Buyer{
        address addr;
        uint amount;
    }

    struct Round {
        address[] buyerAddrs;
        mapping(address=>Buyer) buyers;
    }

    mapping(uint => Round) rounds;

    function getRoundIndex() constant returns (uint){
        return block.number/blocksPerRound;
    }

    function getBuyerAddrs() constant returns (address[]){
        return rounds[getRoundIndex()].buyerAddrs;
    }


function addBuyer(address buyerAddr,uint buyerAmount) constant returns(address[]){

    var roundIndex = getRoundIndex();
    var buyerExists = false;
    var buyerIndex = 0;
    var buyersLength = rounds[roundIndex].buyerAddrs.length;

    rounds[roundIndex].buyerAddrs.length++;
    rounds[roundIndex].buyerAddrs[buyersLength]=buyerAddr;

    return rounds[roundIndex].buyerAddrs;

    //rounds[roundIndex].buyers[buyerAddr] = Buyer(buyerAddr,buyerAmount);

}

    function getBuyersLength() constant returns(uint){
        return rounds[getRoundIndex()].buyerAddrs.length;
    }

}
```

**Comment by chriseth** [comment]
This is the right place, but checking that constant functions do not modify storage is just not implemented yet: https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#subcurrency-example (search for "constant" in that paragraph)

**Comment by aakilfernandes** [comment]
Strange, it is actually enforced in solc (the difference between the realtime compiler and solc is how I found the bug to begin with).
