### ISSUE TITLE
Option to use spaces instead of tabs

### ISSUE THREAD

**Issue by ethernomad** [chriseth/browser-solidity#41]
A lot of people (myself included) prefer indentation to be 2 spaces instead of tabs. Is it possible for this to be an option?

**Comment by axic** [comment]
I think browser-solidity should follow the [style guide](http://solidity.readthedocs.io/en/latest/style-guide.html#indentation): it recommends 4 spaces.

See https://github.com/ethereum/browser-solidity/issues/144
