### ISSUE TITLE
Option to disable compilation.

### ISSUE THREAD

**Issue by chriseth** [chriseth/browser-solidity#44]

**Comment by d11e9** [comment]
Something to keep I mind for this issue, if compilation does not happen then warnings and errors are not shown

**Comment by ethernomad** [comment]
Ideally the red Xs would still appear, but the compilation would not occur when the right pane is hidden.

**Comment by chriseth** [comment]
Ideally, yes ;-)

**Comment by chriseth** [comment]
Changed the titles, as I think this is a better solution. This way, we also do not lose the current state if the source is changed.

**Comment by axic** [comment]
Tracked in https://github.com/ethereum/browser-solidity/issues/101.
