### ISSUE TITLE
sender choice is not used

### ISSUE THREAD

**Issue by koeppelmann** [chriseth/browser-solidity#48]
I tried to interact with a contract but I got the "Error: could not unlock signer account" However, I figured out that the tool was trying to send from eth.accounts[0] although I had selected a different account in the drop down

![bildschirmfoto 2015-10-13 um 23 18 07](https://cloud.githubusercontent.com/assets/2594089/10476240/bbd67062-7200-11e5-9e14-096f878913f7.png)

**Comment by d11e9** [comment]
@koeppelmann thanks for reporting it
