### ISSUE TITLE
Show gas estimated for actions

### ISSUE THREAD

**Issue by d11e9** [chriseth/browser-solidity#5]
tag: feature-request

It would be awesome to show gas estimates for actions taken, in much the same way as you currently show gas estimation for creation.

I find myself compiling and refactoring while checking gas estimates to inform design.

**Comment by ethernomad** [comment]
It already attempts to show gas estimates for functions, but you can't really predict this except for really simple functions.

If it showed how much gas was used when a function was actually executed that would be awesome.

**Comment by d11e9** [comment]
@drupalnomad i added this feature to http://github.com/d11e9/universal-dapp :) will try get the change back into browser-solidity when i get a chance

**Comment by d11e9** [comment]
Featureset merged in #29
