### ISSUE TITLE
Option to to calls against the chain

### ISSUE THREAD

**Issue by koeppelmann** [chriseth/browser-solidity#51]
Not a bug but a feature request - should they be posted here or should I use another place?
It would be nice to "test" a transaction (to a contract on the blockchain) by first doing a call instead of an transaction.

Also I created an transaction from the interface to a blockchain contract but the gas set was to little. So it should a) calculate the gas costs beforehand or b) just give the option to set the gas amount for the transaction where you also select the "from" address.

**Comment by d11e9** [comment]
I'm looking to solve the gas cost issues in the `accounts` branch. regarding. Re test/call transactions, looking into it (its hard to add features without making the ui even more complicated) :)

**Comment by gaetanocaruana** [comment]
any updates on this please?

**Comment by axic** [comment]
The gas costs issues are fixed.  The option to do them as a call is tracked at https://github.com/ethereum/browser-solidity/issues/146.
