### ISSUE TITLE
Enable compliance with Solidity v1.0.0 && v1.0.1

### ISSUE THREAD

**Issue by VoR0220** [chriseth/browser-solidity#53]
For the purposes of legacy code/demos...would this be a difficult thing to do at all?

**Comment by chriseth** [comment]
It should be doable to create a js binary for that version.
Basically, it only has to be extracted from an older commit to this repository, but we might not exactly hit a certain version.

**Comment by chriseth** [comment]
I was able to salvage v0.1.1, but v0.1.0 was compiled in a different way, we have to recompile it if we want to have it.

**Comment by VoR0220** [comment]
alright. Thanks for that. Is this in the latest npm update?

**Comment by d11e9** [comment]
Yes `solc@0.1.6-1` on npm.

**Comment by d11e9** [comment]
hmmm, actually the npm module does not provide a way to explicitly change version. Looking into it.

**Comment by VoR0220** [comment]
Awesome. Good work guys.
