### ISSUE TITLE
Add @why3 tag as recognized

### ISSUE THREAD

**Issue by patcon** [chriseth/browser-solidity#65]
Seeing this on the live version while playing with formal verification:
https://imgur.com/0JGaFQr

**Comment by chriseth** [comment]
It works for me with version "v0.1.6-2015-10-26", which should have been the latest version at the time you created the issue. Can you check which version you use? Perhaps reloading helps. Otherwise, please post the source code.

**Comment by patcon** [comment]
Ah, sorted it out. Adding a space raised the error. Not sure if tha'ts intended, although I see you did that in your example that you posted (ie. `///@why`)

This raises the error for me:

```
contract SimpleStorage {
    uint storedData;

    /**
    * @why
    *
    */
    function set(uint x) {
        storedData = x;
    }

    /**
    * @why
    *
    */
    function get() constant returns (uint retVal) {
        return storedData;
    }
}
```

**Comment by chriseth** [comment]
Note that you used `@why` and not `@why3` - does that fix it?

**Comment by patcon** [comment]
:/

Aaaaand I'm a dolt. Thanks Chris :)
