### ISSUE TITLE
When using "eth_call" parameters are not encoded in request

### ISSUE THREAD

**Issue by ybbus** [chriseth/browser-solidity#72]
When deploying a contract and trying to call a function the parameters of this function are not inserted into the rpc post request.

This is the signature of the function:
7f92a3fe getMeetingName(uint256)

I call this function with this parameter: 12345

And the post request that the browser-solidity tool generates looks like this:
{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x0964a19532f9ad347285cfa72889cdef00646486","data":"0x7f92a3fe0000000000000000000000000000000000000000000000000000000000000000"},"latest"],"id":1181}

You see that the parameter is not included in the data section.

Any idea?

**Comment by axic** [comment]
This seems to be working for the last couple of months.
