### ISSUE TITLE
Abstract contracts should not have create button

### ISSUE THREAD

**Issue by ruchevits** [chriseth/browser-solidity#77]
<details> 
<summary>

Passing extra parameters (e.g. needed zero - passed one, needed one - passed two) to the ancestor contract causes an exception.</summary>

![case1](http://i.imgur.com/Ve75qg4.png)

``` javascript
contract valuable {
    function valuable() {}
}
contract security is valuable(1) {}
```

</details>

<details> 
<summary>

Not passing any parameters to the ancestor contract which expects at least one causes UI problems.</summary>

``` javascript
contract valuable {
    function valuable(uint name) {}
}
contract security is valuable {}
```

![case2](http://i.imgur.com/LXgkeBq.png)
</details>

<details> 
<summary>

Passing less parameters than needed (but not zero) is treated correctly.</summary>

![case3](http://i.imgur.com/pjSfpxl.png)
</details>

**Comment by chriseth** [comment]
Fixed the first case in github.com/ethereum/solidity#289 - the second case should not have a create button at all (and not only one without text), changed the title of this issue accordingly.
