### ISSUE TITLE
Split solc into its own project

### ISSUE THREAD

**Issue by axic** [chriseth/browser-solidity#83]
I think it would make sense to have solc.js or node-solc its own project as it is being used by others now and not necessarily in the context of browser tools.
- [x] create proper npm package / build instructions
- [x] load binaries from https://github.com/ethereum/solc-bin
- [x] move npm packge to https://github.com/ethereum/solc-js

**Comment by axic** [comment]
How to keep references to the other files in browser-solidity:
1) use Jekyll to generate the page
2) or use git submodules

**Comment by axic** [comment]
@chriseth I think this still makes sense, to split `solc` and browser-solidity.

Happy to help if needed

**Comment by chriseth** [comment]
Preliminary code is here: https://github.com/ethereum/solc-js/tree/solc-core

**Comment by d11e9** [comment]
Could we not have maintained the git history 😟

**Comment by axic** [comment]
@d11e9 yep, @chriseth was concerned about the repo size and I didn't find a proper way to purge unneeded references (i.e. removing the binaries from the git history didn't fully purge them from the git objects tree)

**Comment by chriseth** [comment]
@axic that is unfortunate. We should definitely keep the history for browser-solidity (i.e. the html app).
