### ISSUE TITLE
naming a contract field "size" triggers a bug

### ISSUE THREAD

**Issue by ghost** [chriseth/browser-solidity#85]
contract Test {
    int size = 0;

```
function inc() returns (int newSize) {
    return ++size;
}

function get() returns (int size) {
    return size;
}
```

}

When you deploy this contract and call inc() everything works fine, but when you call get() after inc() the returned value is always 0. Changing the name of the field fixes the bug.

**Comment by chriseth** [comment]
The variable `size` in `get` references the return variable declared in the same function, which is initialised to zero, and not the state variable.
