### ISSUE TITLE
Logging does not use any gas

### ISSUE THREAD

**Issue by ethernomad** [chriseth/browser-solidity#86]
http://etherscan.io/tx/0xd8fef6e84e4dc0dc5e73a0147deb4d51d64e1c16354f4d9a45b266c881f513fa

That transaction uses 1026277 gas, but the same transaction in browser-solidity only uses 169297 gas.

The transaction is logging 12800 bytes.

**Comment by axic** [comment]
Do you have a sample source code which exhibits this problem?

**Comment by axic** [comment]
@ethernomad I cannot reproduce this issue. Please reopen in https://github.com/ethereum/browser-solidity if it still persists.
