### ISSUE TITLE
Increasing Memory Size

### ISSUE THREAD

**Issue by SilentCicero** [chriseth/browser-solidity#88]
How can I increase the memory size for SOLC? I'm getting a few stack-too deeps on contracts that are really not very big, but use a lot of inter-contractual calls. I remember there are some hard-set memory numbers somewhere, not sure where they are though. I have a feeling I need to recompile the compiler.

**Comment by chriseth** [comment]
This is not an issue of the runtime (especially not of browser-solidity), but a limitation of the code generator. Please try to reduce the number of local variables or move some variables into a struct. Feel free to ask on gitter for details.
