### ISSUE TITLE
uint176 - Identifier not found or not unique

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#89]
I believe the compiler might have some issue around uint176

http://ethereum.stackexchange.com/questions/584/getting-a-solc-error-uint176-identifier-not-found-or-not-unique

**Comment by aakilfernandes** [comment]
Hi, has this been closed because its fixed or because its an upstream issue?

**Comment by chriseth** [comment]
This was fixed some weeks ago.
