### ISSUE TITLE
solc.compile hanging inexplicably on specific, legal, function signature

### ISSUE THREAD

**Issue by aaronstjohn** [chriseth/browser-solidity#92]
I've found that calls to solc.compile are hanging on contracts with very specific signatures. 

note: I'm using solc version 0.2.0-1. 

The following contract:

```
contract TwoStringInternal{

    function twoString1(string str1, string str2)  internal  
    {

    }
}
```

Causes  solc.compile to hang indefinitely when supplied as input.

Yet, with the slight adjustment:

```
contract TwoStringInternal{
    //      I Added another character here
    //                 V
    function twoString12(string str1, string str2)  internal  
    {

    }
}
```

The same exact call to solc.compile works perfectly fine.

Similarly, I've found that doing any of the following adjustments to the first code segment will cause solc.compile to exit with no problems.
1.  Adding additional characters to the function's name
2.  Removing a string argument
3.  Removing the 'internal' access modifier.

It's baffling to me why this specific signature, puts solc.compile into an infinite hang.

I've been running the compiler via node directly (see code below). The very same code works fine using the browser editor.

For reference, this is the code I'm using to compile:

```
var solc = require('solc');
var fs = require("fs");
var input = {};

//input['TwoStringInternalCompiles'] = fs.readFileSync("./TwoStringInternal_compiles.sol", {encoding: "utf8"});
input['TwoStringInternalDoesntCompile'] = fs.readFileSync("./TwoStringInternal_doesnt_compile.sol", {encoding: "utf8"});

//console.log("Compiling code: "+input['TwoStringInternalCompiles']);
console.log("Compiling code: "+input['TwoStringInternalDoesntCompile']);

var output = solc.compile({sources: input}, 1);
console.log("Compilation completed");
for (var contractName in output.contracts)
   console.log(contractName + ': ' + output.contracts[contractName].bytecode);
```

**Comment by chriseth** [comment]
Unable to reproduce. In the meantime, we changed some parts of the tokenizer, so this could be the reason. Please reopen if the problem persists.
