### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#93]
It looks like there's been a lot of updates not reflected when installing via npm

**Comment by aakilfernandes** [comment]
Specifically all the bin files

**Comment by d11e9** [comment]
@aakilfernandes npm should be up to date as of 0.2.1-1 :)

**Comment by aakilfernandes** [comment]
@d11e9 The bin file only contains soljson-latest.js. Shouldn't it also contain previously compiled versions?

**Comment by croqaz** [comment]
Please update package to latest 0.2.2 ?

Need this :)

Tnx!

**Comment by d11e9** [comment]
@croqaz see: PR #105
