### ISSUE TITLE
Error encoding arguments: SyntaxError: Unexpected token x

### ISSUE THREAD

**Issue by thejdavid** [chriseth/browser-solidity#95]
Hello,

I'm getting the error Error encoding arguments: SyntaxError: Unexpected token x  whenever i try to input an address type. Is there anything i'm missing ? i doesn't bug when passed as "address"(string) but as it is a string it obviously not working as intended.

**Comment by chriseth** [comment]
You have to enter addresses as `"0x1234...000"`, i.e. as javascript strings. Can you provide specific examples?

**Comment by thejdavid** [comment]
in the end It seems the issue was caused by another sub contract not accepting the address. closing

**Comment by Annammal** [comment]
creation of PresalePool errored: Error encoding arguments: SyntaxError: Unexpected token x in JSON at position 112 in Remix. How to run the PresalePool.sol into the Remix . or is there other possibility to run the contract?

**Comment by Annammal** [comment]
SyntaxError: Unexpected token x in JSON at position 112 in Remix

**Comment by stvenyin** [comment]
hello, my Contract source code:
pragma solidity ^0.4.11;

/**
 * @title Ownable
 * @dev The Ownable contract has an owner address, and provides basic authorization control 
 * functions, this simplifies the implementation of "user permissions". 
 */
contract Ownable {
  address public owner;

  function Ownable() {
    owner = msg.sender;
  }
 
  modifier onlyOwner() {
    if (msg.sender != owner) {
      revert();
    }
    _;
  }
 
  function transferOwnership(address newOwner) onlyOwner {
    if (newOwner != address(0)) {
      owner = newOwner;
    }
  }

}

contract ERC20Basic {
  uint public totalSupply;
  function balanceOf(address who) constant returns (uint);
  function transfer(address to, uint value);
  event Transfer(address indexed from, address indexed to, uint value);
}
 
contract ERC20 is ERC20Basic {
  function allowance(address owner, address spender) constant returns (uint);
  function transferFrom(address from, address to, uint value);
  function approve(address spender, uint value);
  event Approval(address indexed owner, address indexed spender, uint value);
}

contract Airdropper is Ownable {

    function multisend(address _tokenAddr, address[] dests, uint256[] values)
    onlyOwner
    returns (uint256) {
        uint256 i = 0;
        while (i < dests.length) {
           ERC20(_tokenAddr).transfer(dests[i], values[i]);
           i += 1;
        }
        return(i);
    }
}
i'm complete it online,but it always appears:transact to Airdropper.multisend errored: Error encoding arguments: SyntaxError: Unexpected token x in JSON at position 1,
how can I solve this questions?
![image](https://user-images.githubusercontent.com/32395964/35547850-a7425584-05b6-11e8-97e3-1fe344450ba0.png)
i read this code carefully spend me most time,but the question is always don,t solve?

**Comment by stvenyin** [comment]
multisend(address _tokenAddr, address[] dests, uint256[] values)
i.m user multisend("0xca35b7d915458ef540ade6068dfe2f44e8fa733c","0xca35b7d915458ef540ade6068dfe2f44e8fa733c","1000000000000000000") singal send on JavaScript VM Test Network

**Comment by Annammal** [comment]
Hi, you have to wrap params with double quotes, that is going to be fixed soon. I think this will work multisend("0xca35b7d915458ef540ade6068dfe2f44e8fa733c",["0xca35b7d915458ef540ade6068dfe2f44e8fa733c","0xca35b7d915458ef540ade6068dfe2f44e8fa733c"],[10000000,2000000])

**Comment by stvenyin** [comment]
i'm use multisend("0xf2003f3d5bde0f8f3bb6f5689db68827588a8830",["0xf2003f3d5bde0f8f3bb6f5689db68827588a8830","0xf2003f3d5bde0f8f3bb6f5689db68827588a8830"],[1000000,2000000000])

Appeares it:

transact to StandardToken.multisend pending ... 
transact to StandardToken.multisend errored: Error: gas required exceeds allowance or always failing transaction
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:93936:44
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:72345:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:11758:16
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16600:29)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12243:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:11758:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12278:25)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12287:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:14467:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12317:16)
    at RpcEngine._runReturnHandlersUp (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
