### ISSUE TITLE
Add a warning if a modifier doesn't contain "_" in function body

### ISSUE THREAD

**Issue by ThePiachu** [chriseth/browser-solidity#96]
I've been writing some test scripts in the Browser Solidity and wondering why the actual contract didn't operate as I expected it. Turns out I didn't notice my modifier should have "_" where I want the code to be executed. Perhaps it would be useful to add a warning to the editor if a modifier function doesn't have the underscore in its body to bring developer attention to that functionality.

**Comment by chriseth** [comment]
Yes, that is a good one! Can you think of a way to disable the warning if it is actually really intended?

**Comment by ThePiachu** [comment]
Maybe if the user dismisses the warning, it will just be noted to the side as "Suppressed 1 warning, click here to unsuppressed".

**Comment by chriseth** [comment]
Ah sorry, I did not see we are in browser-solidity here. The warning should of course be at the compiler level, and on the UI you cannot really correlate warnings between different compilations of the same or changed source code, so suppressing the warning should be done at the source level. But I think we can do without that for now, modifiers without `_` should be extremely rare.

**Comment by axic** [comment]
@chriseth since we have warnings now in Solidity, I think this bug should be added and tracked in https://github.com/ethereum/solidity

**Comment by chriseth** [comment]
Yes, it's here: https://github.com/ethereum/solidity/issues/647
